inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - lib/*
    - log/*
    - public/*
    - vendor/**/*
    - Gemfile
    - node_modules/node-sass/src/libsass/**/*
  # Rails向けのRails copsを実行。"rubocop -R"と同じ
  Rails:
    enabled: true

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

# "Prefer single-quoted strings when you don't need string interpolation or special symbols."を無効
Style/StringLiterals:
  Enabled: false

# "Line is too long"を無効
Metrics/LineLength:
  Enabled: false

#'frozen_string_literal: true'を無効
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Max: 18

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Lint/Debugger:
  Exclude:
    - 'spec/rails_helper.rb'
